# Generated by Django 2.2.1 on 2019-08-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
